# Generated by Django 5.1.1 on 2024-11-28 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_management', '0002_depositamount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioinstrument',
            name='instrument',
        ),
        migrations.RemoveField(
            model_name='portfolioinstrument',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='name',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='average_price',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='instrument',
            field=models.CharField(default='EUR_USD', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='quantity',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Instrument',
        ),
        migrations.DeleteModel(
            name='PortfolioInstrument',
        ),
    ]
