# Generated by Django 5.1.1 on 2024-11-28 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_management', '0003_remove_portfolioinstrument_instrument_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='average_price',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='quantity',
            field=models.BigIntegerField(default=0),
        ),
    ]
