# Generated by Django 5.1.1 on 2024-11-28 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_management', '0005_amountdetails_delete_depositamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amountdetails',
            name='cash_amount',
            field=models.DecimalField(decimal_places=5, max_digits=50),
        ),
        migrations.AlterField(
            model_name='amountdetails',
            name='used_amount',
            field=models.DecimalField(decimal_places=5, max_digits=50),
        ),
    ]
