# Generated by Django 5.1.1 on 2024-11-27 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='filled_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partially_filled', 'Partially Filled'), ('filled', 'Filled')], default='pending', max_length=20),
        ),
    ]
