# Generated by Django 5.1.1 on 2024-11-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_source',
            field=models.CharField(choices=[('manual', 'manual'), ('automated', 'automated')], default='manual', max_length=20),
        ),
    ]
