# Generated by Django 5.1.1 on 2024-11-27 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0002_order_filled_quantity_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='filled_quantity',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
