# Generated by Django 5.1.1 on 2024-11-27 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0004_alter_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='filled_quantity',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.BigIntegerField(),
        ),
    ]
