# Generated by Django 5.1.1 on 2024-11-28 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0006_order_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user',
        ),
    ]
