name: Django CI/CD Pipeline

on:
  push:
    branches:
      - nikhil_raja
  pull_request:
    branches:
      - nikhil_raja

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: stock_trading
          MYSQL_USER: django
          MYSQL_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Wait for MySQL to start
      - name: Wait for MySQL
        run: sleep 30

      # Step 5: Set up the database
      - name: Apply migrations
        env:
          DATABASE_URL: mysql://stock_trading:root@127.0.0.1:3306/stock_trading
        run: |
          python manage.py migrate

      # Step 6: Run tests
      - name: Run tests
        env:
          DATABASE_URL: mysql://stock_trading:root@127.0.0.1:3306/stock_trading
        run: python manage.py test

      # Step 7: Collect static files
      - name: Collect static files
        run: |
          python manage.py collectstatic --noinput
